from prometheus_client import (
    Counter,
    Histogram,
    Gauge,
    CollectorRegistry,
    generate_latest,
    CONTENT_TYPE_LATEST,
    REGISTRY
)
from app.config import settings

# 1. HTTP API Request Metrics
HTTP_REQUESTS_TOTAL = Counter(
    "http_requests_total",
    "Total count of HTTP requests handled by the API.",
    ["endpoint", "method", "status_code"],
    registry=REGISTRY
)

HTTP_REQUEST_DURATION_SECONDS = Histogram(
    "http_request_duration_seconds",
    "HTTP request latency in seconds.",
    ["endpoint"],
    buckets=[0.005, 0.01, 0.025, 0.05, 0.075, 0.1, 0.25, 0.5, 0.75, 1.0, 2.5, 5.0],
    registry=REGISTRY
)

# 2. AI Model Inference Metrics
MODEL_INFERENCE_DURATION_SECONDS = Histogram(
    "model_inference_duration_seconds",
    "Pure ONNX Runtime inference execution latency in seconds.",
    ["inference_type"],  # 'single' or 'batch'
    buckets=[0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0],
    registry=REGISTRY
)

MODEL_PREDICTIONS_TOTAL = Counter(
    "model_predictions_total",
    "Total count of predictions generated by the intent model.",
    ["intent"],
    registry=REGISTRY
)

MODEL_PREDICTION_CONFIDENCE = Histogram(
    "model_prediction_confidence",
    "Distribution of prediction confidence scores (softmax probability).",
    buckets=[0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 0.95, 1.0],
    registry=REGISTRY
)

MODEL_OOS_PREDICTIONS_TOTAL = Counter(
    "model_oos_predictions_total",
    "Total count of out-of-scope (OOS, class 42) predictions.",
    registry=REGISTRY
)

MODEL_IN_SCOPE_PREDICTIONS_TOTAL = Counter(
    "model_in_scope_predictions_total",
    "Total count of in-scope predictions (classes != 42).",
    registry=REGISTRY
)

# 3. Model Info Gauge
MODEL_INFO = Gauge(
    "model_info",
    "Metadata information for the active model checkpoint.",
    ["model_name", "model_version", "task", "backend"],
    registry=REGISTRY
)

# Initialize constant model_info gauge
MODEL_INFO.labels(
    model_name="distilbert_clinc150",
    model_version=settings.MODEL_VERSION,
    task="intent-classification",
    backend="onnxruntime"
).set(1.0)


def get_metrics_content() -> tuple[bytes, str]:
    """Generates latest Prometheus metrics exposition data and content type header."""
    return generate_latest(REGISTRY), CONTENT_TYPE_LATEST
